spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture_recommendation?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ??? ?? ?? ? ??
    show-sql: true       # SQL ?? ??
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # (??) ?? ?? ??
  server:
    port: 8080
